export const workOrderDetailCopy = {
  header: {
    backLabel: 'Back to Work Orders',
    editLabel: 'Edit',
    printLabel: 'Print',
    deleteLabel: 'Delete',
  },
  tabs: {
    information: 'Information',
    materials: 'Materials',
    tasks: 'Tasks',
    otherCosts: 'Other Costs',
    attachments: 'Attachments',
  },
  information: {
    sectionTitle: 'Work Order Details',
    asset: 'Asset',
    location: 'Location',
    description: 'Description',
    type: 'Type',
    priority: 'Priority',
    status: 'Status',
    expectedStartDate: 'Expected Start Date',
    expectedEndDate: 'Expected End Date',
    createdAt: 'Created At',
    updatedAt: 'Last Updated',
  },
  materials: {
    sectionTitle: 'Materials',
    empty: 'No materials added',
    columns: {
      name: 'Material',
      planQty: 'Plan Qty',
      actualQty: 'Actual Qty',
      unitCost: 'Unit Cost',
      totalPlanCost: 'Total Plan',
      totalActualCost: 'Total Actual',
    },
    totalLabel: 'Total',
  },
  tasks: {
    sectionTitle: 'Tasks',
    empty: 'No tasks added',
    columns: {
      description: 'Description',
      status: 'Status',
      assignees: 'Assignees',
      planTime: 'Plan Time',
      actualTime: 'Actual Time',
      type: 'Result',
      required: 'Required',
    },
  },
  otherCosts: {
    sectionTitle: 'Other Costs',
    empty: 'No other costs added',
    columns: {
      description: 'Description',
      quantity: 'Quantity',
      cost: 'Cost',
    },
    totalLabel: 'Total',
  },
  attachments: {
    sectionTitle: 'Attachments',
    empty: 'No attachments',
    uploadLabel: 'Upload Files',
  },
}
