// Generate OpenAPI types into src/generated/openapi.ts
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const PRESETS = {
  app: 'http://localhost:4002/swagger-json',
  admin: 'http://localhost:4001/swagger-json',
}

// CLI usage:
//   pnpm --filter @justdx/types generate           -> uses PRESETS.app
//   pnpm --filter @justdx/types generate app       -> uses PRESETS.app
//   pnpm --filter @justdx/types generate admin     -> uses PRESETS.admin
//   pnpm --filter @justdx/types generate http://... -> custom URL
const arg = process.argv[2]?.replace(/^--/, '')
const presetUrl = arg && PRESETS[arg] ? PRESETS[arg] : undefined
const cliUrl = arg && !PRESETS[arg] ? arg : undefined
const DEFAULT_URL = PRESETS.app
const source = process.env.OPENAPI_URL || cliUrl || presetUrl || DEFAULT_URL

async function main() {
  console.log(`[openapi] Generating types from ${source}`)

  const ast = await openapiTS(source, { additionalProperties: false })
  const contents = astToString(ast)

  const outDir = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    '..',
    'src',
    'generated',
    presetUrl ? arg : 'app'
  )
  await fs.mkdir(outDir, { recursive: true })

  const outPath = path.join(outDir, 'openapi.ts')
  const header = `/* eslint-disable */
// AUTO-GENERATED BY scripts/generate-openapi.mjs
// Source: ${source}
`

  await fs.writeFile(outPath, `${header}\n${contents}`, 'utf8')
  console.log(`[openapi] Wrote ${outPath} (${contents.length} bytes)`)
}

main().catch((err) => {
  console.error('[openapi] Failed to generate types:', err?.message ?? err)
  console.error(
    'Usage: pnpm --filter @justdx/types generate [app|admin|<openapi-url>] (or set OPENAPI_URL)'
  )
  console.error('Presets:', PRESETS)
  process.exit(1)
})
